#! /bin/bash -x

ABSOLUTE_PATH=$(readlink -f $0)
DOTFILES="${ABSOLUTE_PATH%/*}"
mkdir -p ~/.ssh
mkdir -p ~/.config
mkdir -p ~/bin

rm -rf ~/.vim
rm -rf ~/.fonts
rm -rf ~/.emacs.d
rm -rf ~/.config/awesome

ln -sf $DOTFILES/fonts ~/.fonts
ln -sf $DOTFILES/fonts.conf ~/.fonts.conf
ln -sf $DOTFILES/xinitrc ~/.xinitrc
ln -sf $DOTFILES/ssh_config ~/.ssh/config
ln -sf $DOTFILES/zsh/env ~/.zshenv
ln -sf $DOTFILES/zshrc ~/.zshrc
ln -sf $DOTFILES/vim ~/.vim
ln -sf $DOTFILES/vimrc ~/.vimrc
ln -sf $DOTFILES/ackrc ~/.ackrc
ln -sf $DOTFILES/gitconfig ~/.gitconfig
ln -sf $DOTFILES/tmux.conf ~/.tmux.conf
ln -sf $DOTFILES/awesome ~/.config/awesome
ln -sf $DOTFILES/emacs.d ~/.emacs.d
ln -sf $DOTFILES/xresources ~/.Xresources
ln -sf $DOTFILES/chrome ~/bin/

# install vcprompt
if [ ! -f ~/bin/vcprompt ]; then
	echo "install vcprompt";
	cd /tmp;
	wget -c https://github.com/djl/vcprompt/raw/master/bin/vcprompt --no-check-certificate
	chmod +x vcprompt;
	mv vcprompt ~/bin/
fi

if [ ! -f ~/bin/s ]; then
    echo "install ack-grep";
    cd /tmp/
    wget -c http://betterthangrep.com/ack-standalone -O ack-grep
    chmod +x ack-grep
    mv ack-grep ~/bin/s
fi

# Socks proxy, more handy than the above, no setup on the server
# ssh -C2qTnN -D localhost:3218 username@server

# install lein
if [ ! -f ~/bin/lein ]; then
	echo "install lein";
	cd /tmp;
	wget -c https://github.com/technomancy/leiningen/raw/stable/bin/lein --no-check-certificate
	chmod +x lein;
	mv lein ~/bin/
fi
